pipeline {
    agent any

    environment {
        IMAGE = "subhadeep2001/chat-frontend"
        DOCKER_CREDENTIALS_ID = "docker-cred"
        SONAR_TOKEN = credentials('sonar-token')
        DOCKER_PASS = credentials('docker-pass')
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/SubhadeepGhosh2001/Built-a-CI-CD-pipeline-for-Fullstack-App.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                dir('frontend') {
                    sh """
                    sonar-scanner \
                    -Dsonar.projectKey=chat-frontend \
                    -Dsonar.sources=src \
                    -Dsonar.host.url=http://localhost:9000 \
                    -Dsonar.login=${SONAR_TOKEN}
                    """
                }
            }
        }

        stage('Trivy FileSystem Scan') {
            steps {
                sh 'trivy fs --severity HIGH,CRITICAL frontend/ > trivyfs.txt'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build \
                --build-arg VITE_API_URL=http://backend-service:5001/api \
                -t ${IMAGE}:${BUILD_NUMBER} \
                -t ${IMAGE}:latest frontend
                """
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL ${IMAGE}:${BUILD_NUMBER} > trivyimage.txt"
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([string(credentialsId: 'docker-pass', variable: 'DOCKER_PASS')]) {
                    sh """
                    echo \$DOCKER_PASS | docker login -u subhadeep2001 --password-stdin
                    docker push ${IMAGE}:${BUILD_NUMBER}
                    docker push ${IMAGE}:latest
                    """
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                dir('frontend') {
                    sh """
                    kubectl apply -f k8s/
                    kubectl set image deployment/frontend frontend=${IMAGE}:${BUILD_NUMBER}
                    kubectl rollout status deployment/frontend
                    kubectl get pods
                    kubectl get svc
                    """
                }
            }
        }
    }

    post {
        always {
            script {

                def buildStatus = currentBuild.currentResult

                def cause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')
                def buildUser = cause ? cause[0]?.userId : "GitHub Trigger"

                emailext (
                    subject: "Pipeline ${buildStatus}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: """
                        <h2>Jenkins CI/CD Pipeline Report</h2>
                        <p><b>Project:</b> ${env.JOB_NAME}</p>
                        <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                        <p><b>Status:</b> ${buildStatus}</p>
                        <p><b>Triggered By:</b> ${buildUser}</p>
                        <p><b>Build URL:</b> <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                        <hr>
                        <p>Trivy scan reports attached.</p>
                    """,
                    to: 'subhadeepghosh1270@gmail.com',
                    mimeType: 'text/html',
                    attachmentsPattern: 'trivyfs.txt,trivyimage.txt'
                )
            }
        }
    }
}