pipeline {
    agent any

    environment {
        IMAGE = "subhadeep2001/chat-backend"
        SONAR_HOST = "http://localhost:9000"
        EMAIL = "subhadeepghosh1270@gmail.com"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/SubhadeepGhosh2001/Built-a-CI-CD-pipeline-for-Fullstack-App.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    dir('backend') {
                        sh """
                        sonar-scanner \
                        -Dsonar.projectKey=Chat-Backend \
                        -Dsonar.sources=src \
                        -Dsonar.host.url=$SONAR_HOST \
                        -Dsonar.login=$SONAR_TOKEN
                        """
                    }
                }
            }
        }

        stage('Trivy FileSystem Scan') {
            steps {
                dir('backend') {
                    sh 'trivy fs --format table -o trivyfs.txt .'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh """
                    docker build -t $IMAGE:${BUILD_NUMBER} .
                    """
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image --format table -o trivyimage.txt $IMAGE:${BUILD_NUMBER}'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS')]) {

                    sh """
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE:${BUILD_NUMBER}
                    docker tag $IMAGE:${BUILD_NUMBER} $IMAGE:latest
                    docker push $IMAGE:latest                    
                    """
                }
            }
        }

       stage('Deploy to Minikube') {
    steps {
        dir('backend') {
            sh """
            echo "Updating Kubernetes Secret from .env..."
            kubectl delete secret backend-secret --ignore-not-found
            kubectl create secret generic backend-secret --from-env-file=.env

            echo "Applying Kubernetes manifests..."
            kubectl apply -f k8s/

            echo "Updating backend image..."
            kubectl set image deployment/backend backend=$IMAGE:${BUILD_NUMBER}

            echo "Waiting for rollout..."
            kubectl rollout status deployment/backend

            kubectl get pods
            kubectl get svc
            """
        }
    }
}
    }

    post {
        always {
            emailext (
                subject: "Backend Pipeline ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    Backend CI/CD Pipeline Result:
                    Status: ${currentBuild.currentResult}
                    Build: ${env.BUILD_NUMBER}
                    URL: ${env.BUILD_URL}
                """,
                to: 'subhadeepghosh1270@gmail.com',
                attachmentsPattern: 'backend/trivyfs.txt,backend/trivyimage.txt'
            )
        }
    }
}