pipeline {
    agent any

    environment {
        IMAGE = "subhadeep2001/chat-backend"
        DOCKER_CREDENTIALS_ID = "docker-pass"
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/SubhadeepGhosh2001/Built-a-CI-CD-pipeline-for-Fullstack-App.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    dir('backend') {
                        sh """
                        sonar-scanner \
                        -Dsonar.projectKey=Chat-Backend \
                        -Dsonar.sources=src \
                        -Dsonar.host.url=$SONAR_HOST \
                        -Dsonar.login=$SONAR_TOKEN
                        """
                    }
                }
            }
        }

        stage('Trivy FileSystem Scan') {
            steps {
                dir('backend') {
                    sh 'trivy fs --format table -o trivyfs.txt .'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh """
                    docker build -t $IMAGE:${BUILD_NUMBER} .
                    """
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image --format table -o trivyimage.txt $IMAGE:${BUILD_NUMBER}'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS')]) {

                    sh """
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE:${BUILD_NUMBER}
                    """
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                sh """
                kubectl set image deployment/backend backend=$IMAGE:${BUILD_NUMBER}
                kubectl rollout status deployment/backend
                """
            }
        }
    }

    post {
        always {
            emailext (
                subject: "Backend Pipeline ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    Backend CI/CD Pipeline Result:
                    Status: ${currentBuild.currentResult}
                    Build: ${env.BUILD_NUMBER}
                    URL: ${env.BUILD_URL}
                """,
                to: 'subhadeepghosh1270@gmail.com',
                attachmentsPattern: 'backend/trivyfs.txt,backend/trivyimage.txt'
            )
        }
    }
}